---
- hosts: satish
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
    - name: apache status
      service: name=apache2 state=running enabled=yes

